### ISSUE TITLE
Training Time and GPU Usage for GRAB and Arctic Datasets

### ISSUE THREAD

**Issue by ZhaoLizz** [Meowuu7/GeneOH-Diffusion#7]
Hi Xueyi,

First of all, thank you for sharing your code. It's been really helpful.

Could you please share how much time it took to train the model for Stage 1 (motion) and Stage 2 (spatial) for GRAB and Arctic datasets respectively? Which GPU(s) did you use for training?

Moreover, it would be super super great if you could share the model checkpoint trained on the arctic dataset, as well as the arctic dataset script!

Thanks again for your valuable work and for helping the community. Looking forward to your response!

**Comment by Meowuu7** [comment]
Hi @ZhaoLizz ,

Thank you for your interest in our work. I apologize for any inconvenience, as it's been a while since I was working on GeneOH, so I may not recall many details, and finding specific checkpoints from our server's messy storeage might be challenging. As a result, I can only provide general responses to your questions.

Regarding training time and CUDA memory consumption, it takes about one day to train the stage 1 model while two to three days to train the stage two model (for both GRAB and ARCTIC? or training on ARCTIC would cost less time due to the reduced data amount. I cannot remember clearly, sorry for that.). A single 3090 GPU with 24GB of memory is sufficient for training. 

Unfortunately, I don’t currently have the bandwidth to continue working on this project, and I am unable to locate the checkpoint for ARCTIC at this time. Additionally, organizing the original scripts is difficult, as they were quite messy during the project, and revisiting the project's context would be too time-consuming. I suggest you modifying the existing codebase to support ARCTIC by adapting the data loaders for GRAB, TACO, or HOI4D to work with ARCTIC. Once this is done, the training and evaluation processes are similar across these datasets. 

Please feel free to reach out if you encounter any issues, and I’d do my best to assist you in resolving them, within the limits of my available time and energy. 

Thanks for your understanding, 
Best wishes and good luck

**Comment by ZhaoLizz** [comment]
Thanks for the kind reply! 
Best wishes
